CREATE TABLE IF NOT EXISTS usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS status (
  id INT PRIMARY KEY,
  nome VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tarefa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL,
  criado_por INT NOT NULL,
  status_id INT NOT NULL,
  finalizado_em TIMESTAMP NULL,
  finalizado_por INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_tarefa_criado_por FOREIGN KEY (criado_por) REFERENCES usuario(id),
  CONSTRAINT fk_tarefa_status FOREIGN KEY (status_id) REFERENCES status(id),
  CONSTRAINT fk_tarefa_finalizado_por FOREIGN KEY (finalizado_por) REFERENCES usuario(id)
);
